### ISSUE TITLE
Payment indexing and tx.metadata.existed issue

### ISSUE THREAD

**Issue by kulpreet** [libbitcoin/libbitcoin-blockchain#498] opened 2019-02-22 12:08 UTC
# Observed Behaviour

With the database::catalog code in place, the blockchain::catalog_block method is still not properly cataloging payments when a block is set candidate.

Payment cataloging works if block_pool::blocks_ cache is enabled by setting block_buffer_limit to > 0. However, with caching disabled (block_buffer_limit set to 0) transaction catalog fails.

# Diagnosis

When block_pool cache is disabled, the organize_block::handle_check handler is called with a height, and that requires block_chain to fetch the block and the transactions from the database. However, when fetching the transactions from the database, the tx.metadata.existed is always explicitly set to true in the transaction_result::transaction method.

The existed metadata flag is not saved to database on transaction_database::store. So we end up with the situation that payments are never cataloged as tx.metadata.existed is first checked to skip transaction cataloging.

## block_pool cache

If block_pool caching is used then tx.metadata.existed will be properly set as it is the same in memory object. However, by default the block_buffer_limit is set to 0 to bs.cfg. This will result in payment cataloging failing.

# Possible solutions

1. We can save the existed flag in the transaction metadata on storize and then reload it in transaction_result::transaction. But this will require an extra byte for each transaction.

2.  An alternative is to catalog payments for transactions in a block from block_chain::catalog(block). This will happen where block_chain is currently calling database::catalog(block). block_chain::catalog(block) will read if the tx.metadata.candidate is false && tx.metadata.height == rule_fork::unverified, if so then it will keep the transactions that need to be cataloged in a list and directly call database::catalog(tx) immediately after calling database::candidate(block) for all the transactions in the list.

To me, 2 sounds too complex and 1 requires extra storage. Maybe there is another way to do this that i am missing. Any ideas on how to resolve this? I am going to write some block_chain tests for these two cases and try and be ready to incorporate a fix.

@evoskuil - need your help here a bit to decide how to resolve this.

**Comment by thecodefactory** [comment] 2019-02-22 12:54
@kulpreet Thanks for looking into this!

**Comment by kulpreet** [comment] 2019-02-22 13:39
@thecodefactory - I hope I am not getting things wrong in my head ;)

In fact, I was thinking more and I think option 1 above is plain and simple wrong :) The existed flag captures if we read the tx from the database. So to save it and then update it later etc is silly.

Option 2. also has a problem of a race condition where two candidate blocks arrive with the same tx and the tx is read for both threads before the first one writes. Then they will both end up cataloging the payments.

I think it is clear i need to stare at the code some more! :)

**Comment by thecodefactory** [comment] 2019-02-22 13:51
@kulpreet Just working through the problem is great, I'm sure you guys will resolve it.  I'm still operating with that kludgy workaround that ignores that check in order to test the indexing/lookups :sweat_smile:

**Comment by evoskuil** [comment] 2019-02-22 16:58
@kulpreet yes, storing .existed is silly :).

**Comment by evoskuil** [comment] 2019-02-22 17:01
@kulpreet never rely on height to determine whether a tx is confirmed. The tx position sentinel determines whether height stores flags or not.

**Comment by evoskuil** [comment] 2019-02-22 17:09
@kulpreet conceptually what you require is a tx.cataloged flag. When we validate and store an unconfirmed tx (that of course did not previously exist) we catalog it. When we store txs from a block download we don’t, yet they do exist at that point. Given that a confirmed tx can become unconfirmed, confirmation state is not a sufficient indication of cataloged state.

**Comment by evoskuil** [comment] 2019-02-22 17:17
The one state in which a tx is not cataloged is when it is first downloaded in association with a pending block. Yet an unconfirmed tx carries no indication of whether it is pending vs. deconfirmed. As such the required indication is missing.

**Comment by kulpreet** [comment] 2019-02-22 17:30
> The downside to this is in the added complexity of testing the confirmed state.

We will have to test the s*%t out of it.

I like using the sentinel approach as it saves space, and yes, we should put it in the tx database, so the complication doesn't leak into block_chain.

Just another question. A tx is also cataloged when the block/tx candidated, not confirmed. Just want to confirm there wasn't a typo there or something I am not clear about yet. The confirmation might happen immediately after it is candidated, but the cataloging work is happening at the time of candidating it.

**Comment by evoskuil** [comment] 2019-02-22 17:41
Right

**Comment by kulpreet** [comment] 2019-02-22 18:00
I seem to be going in circles with the aysnc part, so want to clarify it here and keep it as a future note for me too. 

The block_pool seems to be using resubscriber::relay to start the organize_block::handle_fetch operation. Which means we don't need to worry about stale reads of tx.position sentinel in the rare case two blocks come in with the same tx. Is my understanding correct here?

I am also aware that the second block will not get validated if it has a transaction that has already been confirmed. But I still wanted to ask.

**Comment by evoskuil** [comment] 2019-02-22 18:17
A block with a currently-confirmed (including candidate) tx is invalid. An invalid block will of course fail validation and therefore will not be confirmed.

Given that validation and confirmation occur under the same critical section (and shares a mutex with tax pool critical section) there is no chance of state reads except possibly in the case of the read-ahead cache, which spans independent validations. But in the case of a reorg the set of cached blocks must be either consistent or new, so there should be no issue.

**Comment by kulpreet** [comment] 2019-03-05 17:10
With PRs https://github.com/libbitcoin/libbitcoin-database/pull/271 and https://github.com/libbitcoin/libbitcoin-blockchain/pull/499 I am able to run a bs instance that is indexing payments and am able to query using fetch-history from the master branch of libbitcoin-explorer.

**Comment by thecodefactory** [comment] 2019-06-04 13:11
@kulpreet Merged https://github.com/libbitcoin/libbitcoin-database/pull/271 and https://github.com/libbitcoin/libbitcoin-blockchain/pull/499

**Closed by thecodefactory** 2019-06-04 13:11 UTC
